import { NutritionMasterItem } from './types';

export const FALLBACK_NUTRITION_DATA: NutritionMasterItem[] = [
  {
    food_code: 'NASI_PUTIH',
    food_name: 'Nasi Putih',
    category: 'Pokok',
    serving_size_gram: 150,
    calories: 195.0,
    protein: 3.6,
    fat: 0.4,
    carbs: 42.9,
    fiber: 0.3,
    shelf_life_hours: 18,
    spoilage_signs: ['Menguning', 'Bercak merah/pink', 'Berbau asam/basi', 'Berlendir'],
  },
  {
    food_code: 'AYAM_GORENG',
    food_name: 'Ayam Goreng',
    category: 'Lauk Hewani',
    serving_size_gram: 100,
    calories: 260.0,
    protein: 27.0,
    fat: 16.0,
    carbs: 0.0,
    fiber: 0.0,
    shelf_life_hours: 24,
    spoilage_signs: ['Warna keabuan di dekat tulang', 'Bau tengik', 'Permukaan lengket'],
  },
  {
    food_code: 'TEMPE_GORENG',
    food_name: 'Tempe Goreng',
    category: 'Lauk Nabati',
    serving_size_gram: 50,
    calories: 118.0,
    protein: 9.0,
    fat: 7.5,
    carbs: 4.0,
    fiber: 1.4,
    shelf_life_hours: 24,
    spoilage_signs: ['Bau amonia tajam', 'Bercak hitam basah berlendir'],
  },
  {
    food_code: 'TAHU_GORENG',
    food_name: 'Tahu Goreng',
    category: 'Lauk Nabati',
    serving_size_gram: 50,
    calories: 58.0,
    protein: 4.8,
    fat: 3.5,
    carbs: 2.1,
    fiber: 0.8,
    shelf_life_hours: 16,
    spoilage_signs: ['Rasa asam', 'Lendir permukaan', 'Tekstur lembek berair'],
  },
  {
    food_code: 'SAYUR_SOP',
    food_name: 'Sayur Sop Bening',
    category: 'Sayur',
    serving_size_gram: 150,
    calories: 45.0,
    protein: 1.5,
    fat: 0.5,
    carbs: 9.0,
    fiber: 1.8,
    shelf_life_hours: 12,
    spoilage_signs: ['Kuah berbusa', 'Kuah keruh asam', 'Sayuran layu berlendir'],
  },
  {
    food_code: 'SAYUR_LODEH',
    food_name: 'Sayur Lodeh (Santan)',
    category: 'Sayur',
    serving_size_gram: 150,
    calories: 120.0,
    protein: 2.8,
    fat: 8.5,
    carbs: 9.2,
    fiber: 2.1,
    shelf_life_hours: 8,
    spoilage_signs: ['Santan pecah menggumpal', 'Berbusa', 'Rasa masam'],
  },
  {
    food_code: 'TELUR_DADAR',
    food_name: 'Telur Dadar',
    category: 'Lauk Hewani',
    serving_size_gram: 60,
    calories: 154.0,
    protein: 9.3,
    fat: 12.0,
    carbs: 1.2,
    fiber: 0.0,
    shelf_life_hours: 16,
    spoilage_signs: ['Tengik', 'Perubahan warna kehijauan gelap', 'Berlendir'],
  },
  {
    food_code: 'SAMBAL_TERASI',
    food_name: 'Sambal Terasi',
    category: 'Pelengkap',
    serving_size_gram: 20,
    calories: 35.0,
    protein: 0.8,
    fat: 2.1,
    carbs: 3.2,
    fiber: 0.5,
    shelf_life_hours: 36,
    spoilage_signs: ['Bintik jamur putih/abu-abu di permukaan', 'Gelembung gas'],
  },
];

export function findFallbackNutrition(query: string): NutritionMasterItem | null {
  const q = query.toLowerCase();
  return (
    FALLBACK_NUTRITION_DATA.find((item) =>
      item.food_name.toLowerCase().includes(q) || item.food_code.toLowerCase().includes(q)
    ) || null
  );
}
